name: Push Notes to Public Repo

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Private Repository
      uses: actions/checkout@v3

    - name: Setup Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Clone Public Repository
      run: |
        git clone https://${{ secrets.PUBLIC_REPO_PAT }}@github.com/juanignaciogiacobbe/apuntes-jig.git public-repo

    - name: Copy Notes to Public Repo
      run: |
        rsync -a --delete ./AWS ./public-repo/docs/
        rsync -a --delete ./Programacion\ Concurrente ./public-repo/docs/
        rsync -a --delete ./Sistemas\ Operativos ./public-repo/docs/

    - name: Rename Files (Remove First 3 Characters)
      run: |
        for dir in AWS Programacion\ Concurrente Sistemas\ Operativos; do
          find "./public-repo/docs/$dir" -type f -name "??-*" | while read -r file; do
            dir_path=$(dirname "$file")
            base_name=$(basename "$file")
            new_name=${base_name:3} # Elimina los primeros 3 caracteres
            mv "$file" "$dir_path/$new_name"
          done
        done

    - name: Convert Callouts
      run: |
        find ./public-repo/docs/ -type f -name "*.md" -exec sed -i \
        -e 's/> \[!NOTE\] \(.*\)/!!! note "\1"/g' \
        -e 's/> \[!IMPORTANT\] \(.*\)/!!! note "\1"/g' \
        -e 's/> \[!TIP\] \(.*\)/!!! tip "\1"/g' \
        -e 's/> \[!WARNING\] \(.*\)/!!! warning "\1"/g' \
        -e 's/> \[!DANGER\] \(.*\)/!!! warning "\1"/g' \
        -e 's/> \[!INFO\] \(.*\)/!!! info "\1"/g' \
        -e 's/> \[!QUOTE\] \(.*\)/!!! quote "\1"/g' {} +


    - name: Commit and Push Changes
      run: |
        cd public-repo
        git add .
        git commit -m "Sync notes from private repo" || echo "No changes to commit"
        git push https://${{ secrets.PUBLIC_REPO_PAT }}@github.com/juanignaciogiacobbe/apuntes-jig.git main
