name: Push Notes to Public Repo

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Private Repository
      uses: actions/checkout@v3

    - name: Setup Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Clone Public Repository
      run: |
        git clone https://${{ secrets.PUBLIC_REPO_PAT }}@github.com/juanignaciogiacobbe/apuntes-jig.git public-repo

    - name: Copy Notes to Public Repo
      run: |
        rsync -a --delete ./AWS ./public-repo/docs/
        rsync -a --delete ./Programación\ Concurrente ./public-repo/docs/
        rsync -a --delete ./Sistemas\ Operativos ./public-repo/docs/


    - name: Convert Callouts
      run: |
        find ./public-repo/docs/ -type f -name "*.md" -exec sed -i \
        -e 's/> \[!NOTE\]/!!! note/g' \
        -e 's/> \[!IMPORTANT\]/!!! note/g' \
        -e 's/> \[!TIP\]/!!! tip/g' \
        -e 's/> \[!WARNING\]/!!! warning/g' \
        -e 's/> \[!INFO\]/!!! info/g' \
        -e 's/> \[!QUOTE\]/!!! quote/g' {} +

    - name: Commit and Push Changes
      run: |
        cd public-repo
        git add .
        git commit -m "Sync notes from private repo" || echo "No changes to commit"
        git push https://${{ secrets.PUBLIC_REPO_PAT }}@github.com/juanignaciogiacobbe/apuntes-jig.git main
